before_script:
  # Do anything you have to do before your stages below here.
  # For example, do you need to change permissions on a build folder
  # or modify a file to insert a variable from your CI config here?
  - mkdir -p /home/gitlab-runner/.ssh
  - chmod 700 /home/gitlab-runner/.ssh
  - echo "$DEPLOY_SSH_KEY"
  - cat $DEPLOY_SSH_KEY
  - cp $DEPLOY_SSH_KEY /home/gitlab-runner/.ssh/gitlab-ci-delivery
  - cat /home/gitlab-runner/.ssh/gitlab-ci-delivery

stages:
# These are the three states we want, building the app, testing it by
# executing unit tests and checking the results, and finally if this
  - build
  # You will need to define this stage somewhere below.
  - test
  # I will provide this example for you below.
  - deploy
  
build:
  image: maven:latest
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - group14/target
  tags:
    - ugrad

test:
  image: maven:latest
  stage: test
  script:
    - mvn clean test
  tags:
    - ugrad


deployStage:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - group14/target
  script:
    
    - ssh -i /home/gitlab-runner/.ssh/gitlab-ci-delivery -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir ${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"

  environment:
    name: Production
  only:
    - master