image: maven:latest

build:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - group14/target
  tags:
    - ugrad

test:
  stage: test
  script:
    - mvn clean test
  tags:
    - ugrad


deployStage:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - group14/target
  script:
    
    - ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir ${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"

  environment:
    name: Production
  only:
    - master