image: maven:latest

build:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - group14/target
  tags:
    - ugrad

test:
  stage: test
  script:
    - mvn clean test
  tags:
    - ugrad

  