image: maven:latest

build:
  image: maven:3.3.9-jdk-8
  stage: build
  tags:
    - ugrad
  artifacts:
    paths:
    - group14/target
  script:
    mvn clean install
    #mvn clean compile

test:
  image: maven:3.3.9-jdk-8
  stage: test
  script:
    - mvn clean test
  tags:
    - ugrad


deployStage:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - group14/target
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - cat /home/gitlab-runner/.ssh/id_rsa
   ## - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${EXECUTABLE_TO_DEPLOY} "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/"
    - ssh -i /users/grad/ashaikh/.ssh/gitlab-ci-delivery -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir ${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    - scp -r -o StrictHostKeyChecking=no group14/target/EMS-1.0-SNAPSHOT.jar "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/"
  environment:
    name: Production
  only:
    - master
  