before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEPLOY_SSH_KEY")
  - mkdir -p ~/.ssh

stages:
# These are the three states we want, building the app, testing it by
# executing unit tests and checking the results, and finally if this
  - build
  # You will need to define this stage somewhere below.
  - test
  # I will provide this example for you below.
  - deploy
  
build:
  image: maven:latest
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - group14/target
  tags:
    - ugrad

test:
  image: maven:latest
  stage: test
  script:
    - mvn clean test
  tags:
    - ugrad


deployStage:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - group14/target
  script:
    
    - ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} "mkdir ${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"

  environment:
    name: Production
  only:
    - master